import { ADE_ABI } from './abis/ADE';
import { LAR_ABI } from './abis/LAR';
import { LENDING_AND_BORROWING_ABI } from './abis/LendingAndBorrowing';

export const CONTRACT_ADDRESSES = {
  ADE_TOKEN: "YOUR_ADE_TOKEN_ADDRESS",
  LAR_TOKEN: "YOUR_LAR_TOKEN_ADDRESS",
  LENDING_AND_BORROWING: "YOUR_LENDING_AND_BORROWING_ADDRESS"
};

export const CONTRACT_ABIS = {
  ADE_TOKEN: ADE_ABI,
  LAR_TOKEN: LAR_ABI,
  LENDING_AND_BORROWING: LENDING_AND_BORROWING_ABI
}; 